package com.lh.system.model.condition;

import java.util.Date;

public class DeptCondition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.dept_name
     *
     * @mbggenerated
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.dept_code
     *
     * @mbggenerated
     */
    private String deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.dept_pid
     *
     * @mbggenerated
     */
    private Integer deptPid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.dept_leader
     *
     * @mbggenerated
     */
    private Integer deptLeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.enabled
     *
     * @mbggenerated
     */
    private Byte enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.create_id
     *
     * @mbggenerated
     */
    private Integer createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.lastModify_time
     *
     * @mbggenerated
     */
    private Date lastmodifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.lastModify_id
     *
     * @mbggenerated
     */
    private Integer lastmodifyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.id
     *
     * @return the value of t_dept.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.id
     *
     * @param id the value for t_dept.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.dept_name
     *
     * @return the value of t_dept.dept_name
     *
     * @mbggenerated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.dept_name
     *
     * @param deptName the value for t_dept.dept_name
     *
     * @mbggenerated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.dept_code
     *
     * @return the value of t_dept.dept_code
     *
     * @mbggenerated
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.dept_code
     *
     * @param deptCode the value for t_dept.dept_code
     *
     * @mbggenerated
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode == null ? null : deptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.dept_pid
     *
     * @return the value of t_dept.dept_pid
     *
     * @mbggenerated
     */
    public Integer getDeptPid() {
        return deptPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.dept_pid
     *
     * @param deptPid the value for t_dept.dept_pid
     *
     * @mbggenerated
     */
    public void setDeptPid(Integer deptPid) {
        this.deptPid = deptPid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.dept_leader
     *
     * @return the value of t_dept.dept_leader
     *
     * @mbggenerated
     */
    public Integer getDeptLeader() {
        return deptLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.dept_leader
     *
     * @param deptLeader the value for t_dept.dept_leader
     *
     * @mbggenerated
     */
    public void setDeptLeader(Integer deptLeader) {
        this.deptLeader = deptLeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.remark
     *
     * @return the value of t_dept.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.remark
     *
     * @param remark the value for t_dept.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.enabled
     *
     * @return the value of t_dept.enabled
     *
     * @mbggenerated
     */
    public Byte getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.enabled
     *
     * @param enabled the value for t_dept.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Byte enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.create_time
     *
     * @return the value of t_dept.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.create_time
     *
     * @param createTime the value for t_dept.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.create_id
     *
     * @return the value of t_dept.create_id
     *
     * @mbggenerated
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.create_id
     *
     * @param createId the value for t_dept.create_id
     *
     * @mbggenerated
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.lastModify_time
     *
     * @return the value of t_dept.lastModify_time
     *
     * @mbggenerated
     */
    public Date getLastmodifyTime() {
        return lastmodifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.lastModify_time
     *
     * @param lastmodifyTime the value for t_dept.lastModify_time
     *
     * @mbggenerated
     */
    public void setLastmodifyTime(Date lastmodifyTime) {
        this.lastmodifyTime = lastmodifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.lastModify_id
     *
     * @return the value of t_dept.lastModify_id
     *
     * @mbggenerated
     */
    public Integer getLastmodifyId() {
        return lastmodifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.lastModify_id
     *
     * @param lastmodifyId the value for t_dept.lastModify_id
     *
     * @mbggenerated
     */
    public void setLastmodifyId(Integer lastmodifyId) {
        this.lastmodifyId = lastmodifyId;
    }
}