package com.lh.system.model;

import java.util.Date;

/**
 * @// TODO: 2021/7/22  用户信息表
 * @author mamei
 */
public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.dept_id
     *
     * @mbggenerated
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.hired
     *
     * @mbggenerated
     */
    private Byte hired;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.enabled
     *
     * @mbggenerated
     */
    private Byte enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.create_Time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.create_id
     *
     * @mbggenerated
     */
    private Integer createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.lastModify_Time
     *
     * @mbggenerated
     */
    private Date lastmodifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.lastModify_id
     *
     * @mbggenerated
     */
    private Integer lastmodifyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.id
     *
     * @return the value of t_users.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.id
     *
     * @param id the value for t_users.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.user_name
     *
     * @return the value of t_users.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.user_name
     *
     * @param userName the value for t_users.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.password
     *
     * @return the value of t_users.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.password
     *
     * @param password the value for t_users.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.real_name
     *
     * @return the value of t_users.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.real_name
     *
     * @param realName the value for t_users.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.dept_id
     *
     * @return the value of t_users.dept_id
     *
     * @mbggenerated
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.dept_id
     *
     * @param deptId the value for t_users.dept_id
     *
     * @mbggenerated
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.phone
     *
     * @return the value of t_users.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.phone
     *
     * @param phone the value for t_users.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.email
     *
     * @return the value of t_users.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.email
     *
     * @param email the value for t_users.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.hired
     *
     * @return the value of t_users.hired
     *
     * @mbggenerated
     */
    public Byte getHired() {
        return hired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.hired
     *
     * @param hired the value for t_users.hired
     *
     * @mbggenerated
     */
    public void setHired(Byte hired) {
        this.hired = hired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.enabled
     *
     * @return the value of t_users.enabled
     *
     * @mbggenerated
     */
    public Byte getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.enabled
     *
     * @param enabled the value for t_users.enabled
     *
     * @mbggenerated
     */
    public void setEnabled(Byte enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.create_Time
     *
     * @return the value of t_users.create_Time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.create_Time
     *
     * @param createTime the value for t_users.create_Time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.create_id
     *
     * @return the value of t_users.create_id
     *
     * @mbggenerated
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.create_id
     *
     * @param createId the value for t_users.create_id
     *
     * @mbggenerated
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.lastModify_Time
     *
     * @return the value of t_users.lastModify_Time
     *
     * @mbggenerated
     */
    public Date getLastmodifyTime() {
        return lastmodifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.lastModify_Time
     *
     * @param lastmodifyTime the value for t_users.lastModify_Time
     *
     * @mbggenerated
     */
    public void setLastmodifyTime(Date lastmodifyTime) {
        this.lastmodifyTime = lastmodifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.lastModify_id
     *
     * @return the value of t_users.lastModify_id
     *
     * @mbggenerated
     */
    public Integer getLastmodifyId() {
        return lastmodifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.lastModify_id
     *
     * @param lastmodifyId the value for t_users.lastModify_id
     *
     * @mbggenerated
     */
    public void setLastmodifyId(Integer lastmodifyId) {
        this.lastmodifyId = lastmodifyId;
    }
}